### ISSUE TITLE
Can't import with node

### ISSUE THREAD

**Issue by plampila-teconer** [pixelmund/svelte-kit-cookie-session#18]
While package works fine with SvelteKit/Vite, it can't be imported as an ESM package with node.

If I understand correctly, there are three changes to make this work:
- Add `"type": "module"` to package.json, so that it's seen as an ESM package.
- Add `"exports": "./dist/index.js"` to package.json, to set what is being exported.
- Use .js extension in internal imports within the package.

My use case for this is handling a WebSocket connection outside the SvelteKit middleware using adapter-node.

**Comment by pixelmund** [comment]
Hey! Thanks for reporting this. I will try to get it resolved later today.

**Comment by pixelmund** [comment]
This should be fixed in `1.3.2`, if you're still running into problems let me know.

**Comment by plampila-teconer** [comment]
Works great. Thank you for the super fast response!

During a svelte-kit build there is a warning that I don't think was there before:
> [vite-plugin-svelte] The following packages did not export their `package.json` file so we could not check the "svelte" field. If 
you had difficulties importing svelte components from a package, then please contact the author and ask them to export the package.json file.

**Comment by pixelmund** [comment]
You're welcome! The warning should be gone in `1.3.3`
