### ISSUE TITLE
Update apis to fit SvelteKit's recent changes

### ISSUE THREAD

**Issue by pixelmund** [pixelmund/svelte-kit-cookie-session#24]

**Comment by OlmoDalco** [comment]
Breaking change in SvelteKit api:
`handle({request,resolve})` has been [replaced](https://kit.svelte.dev/docs#hooks-handle) with `handle({event,resolve}`

**Comment by pixelmund** [comment]
Hey, i'll try to get the required changes in later today. For now you can stick to a previous version of Kit.
