### ISSUE TITLE
Expose "secure" as a cookie option

### ISSUE THREAD

**Issue by seantimm** [pixelmund/svelte-kit-cookie-session#27]
Looks like the underlying cookie library already has support for it, but the "secure" option isn't currently exposed.

**Comment by pixelmund** [comment]
Hey this should now work in `2.0.4`

**Comment by seantimm** [comment]
Thanks! I think the values for these new options need added to the makeCookie function for it to work.

**Comment by pixelmund** [comment]
I'm sorry missed that, it should be fixed in `2.0.5` now!

**Comment by seantimm** [comment]
Working great now - thanks!
