### ISSUE TITLE
getContext({ headers }) no more supported in sveltekit v1.0.0-next.99 ++

### ISSUE THREAD

**Issue by jack-y** [pixelmund/svelte-kit-cookie-session#3]
As said [in your doc](https://github.com/pixelmund/svelte-kit-cookie-session#initializing), the session is initialized with the hook function `getContext({ headers })`.
The recent versions of the sveltekit (1.0.0-next.99 ++) [hooks](https://kit.svelte.dev/docs#hooks) feature don't support this function.
How can we adapt our code to continue to use the svelte-kit-cookie-session package?

Everything works fine with sveltekit version v1.0.0-next.98 and before.

**Comment by pixelmund** [comment]
@jack-y I will take a look later, it should be just as easy as moving the code to handle before the render fn and provide the session in req.locals. I may have some free time later today and publish a new version and update the documentation.
