### ISSUE TITLE
Consider `SameSite=Lax` as a new default

### ISSUE THREAD

**Issue by mrkishi** [pixelmund/svelte-kit-cookie-session#32]
For some reason, we've seen an influx of questions about how to properly handle user session after an OAuth login with SvelteKit. While this isn't exclusive to `svelte-kit-cookie-session`, [your users](https://github.com/pixelmund/svelte-kit-cookie-session/issues/22) are also [unknowingly affected](https://discord.com/channels/457912077277855764/969029242841075773/969035803776938014) because of the `SameSite=Strict` default.

The issue with `SameSite=Strict` is that it is too restrictive for the _vast_ majority of use-cases. It prevents browsers from sending cookies on all requests that originated from a third-party domain, even if indirectly. This is the case for OAuth logins: third-party services usually issue `302` redirects to your callback endpoints where you're likely to further redirect the user to a specific page—but since the redirect chain originated outside your domain, the browser will not send the cookies upon arrival at the target page.

While it does provide more security than `Lax`, its usefulness is dubious for most people. With `Strict`, if a third-party domain even links to your site with a vanilla `<a href="https://www.yoursite.com">Your site</a>` anchor, your users will be logged out when navigating through those links as the cookies will be blocked.

Please, consider switching to `SameSite=Lax` by default as it enables most of the safety guards while not breaking common use-cases.

**Comment by pixelmund** [comment]
Hey @mrkishi 
Thanks for reporting this, i think it makes absolutely sense to make `Lax` the default. 
I'll try to get a new version out very soon!

**Comment by pixelmund** [comment]
This is now the default in v2.1.4
