### ISSUE TITLE
Support for SvelteKit@next-415+

### ISSUE THREAD

**Issue by Starmism** [pixelmund/svelte-kit-cookie-session#42]
SvelteKit 415 had [this extremely breaking change](https://github.com/sveltejs/kit/pull/5946).

Any plans to update to either make your own version of a session, a la [Lucia](https://lucia-sveltekit.vercel.app/changelog), or another replacement?

**Comment by Zamiell** [comment]
For people looking to encrypt their cookies right now, I guess the solution is to manually encrypt your own cookie data in "hooks.ts" using AES or something (e.g. [crypto-js](https://github.com/brix/crypto-js)).

(This library seems to use [zencrypt](https://www.npmjs.com/package/zencrypt) over crypto-js, which seems like a much worse option at first glance.)

**Comment by ranjanified** [comment]
I am interested too in getting this addressed. Please let us know your plans at least, so that we can either try to look for alternatives of wait for the fix. My client side user state is implemented using this library.

**Comment by pixelmund** [comment]
> 

First of all, `zencrypt` uses the WebCrypto API under the hood which SvelteKit already polyfills and is available in the different environments kit supports. It should also be faster than `crypto-js`, which might be more battle tested, for sure.

**Comment by pixelmund** [comment]
I'm actually not sure what to do with the session store for now.  
You can still access your sessions in the `+page.server.js` etc. files and return them for the client in the `+layout.server.js` like so:

```ts
 export const load = (event) => {
  return {
     session: event.locals.session.data // This could also use your previous getSession function
  }
}
```

**Comment by pixelmund** [comment]
I've updated the project to use the new Kit Routing and also gone ahead and updated the README accordingly.
I might consider adding a session store back but i think that's kinda tricky.

**Comment by ranjanified** [comment]
@pixelmund ... `Date` object is failing serialization if returned in `load` response. 

[check_serializability](https://github.com/sveltejs/kit/blob/2e9487ed08f48e10eeb576ac2a31f5db89fdecb9/packages/kit/src/runtime/server/page/load_data.js#L141) has kept `Date` out of consideration and so is throwing.

The `expires` populated on `event.locals.session.data` is adding to this ... Any thoughts please?

**Comment by pixelmund** [comment]
@ranjanified expires is now excluded from the event.locals.session.data getter, it's still beeing tracked internally but doesn't get exposed to the user anymore, you can try it with version `3.1.2`.

**Comment by ranjanified** [comment]
Thanks a lot 🙏 @pixelmund ... Indeed it's working fine now!!!
