### ISSUE TITLE
Document cookie options

### ISSUE THREAD

**Issue by Zamiell** [pixelmund/svelte-kit-cookie-session#45]
![image](https://user-images.githubusercontent.com/5511220/189433986-d4f1e553-fdb0-49b1-af2b-be7606276eab.png)

Here, we see that the "cookie" object is optional.

But in most libraries, there would be nice JSDoc comments here that describe each individual option and the default value that the library chooses for you. (The JSDoc comments would cause mouse-over documentation to appear in VSCode so that I wouldn't have to leave my code editor to search the documentation.)

Can this be added? It's unclear what I need to specify and/or change in order to make using this product secure.

**Comment by pixelmund** [comment]
I have documented the cookie options as well as the other session options in version `3.3.0`

**Comment by Zamiell** [comment]
thanks
