### ISSUE TITLE
Session Cookie not being set in safari

### ISSUE THREAD

**Issue by yoh-extradat** [pixelmund/svelte-kit-cookie-session#46]
Setup everything according to docs and it works like a charm on chrome, firefox and edge.
However the cookie will not be set on safari. Any ideas why or how to solve this issue?

**Comment by pixelmund** [comment]
Hey, sorry for the late response!

Can you try setting the `secure` cookie option to false? I think safari blocks it when not on https

```ts
export const handle = handleSession({
	secret: 'SOME_COMPLEX_SECRET_AT_LEAST_32_CHARS',
        cookie: {
            secure: false
        }
});
```

**Comment by pixelmund** [comment]
The default for `cookie.secure` is now false while in dev
