### ISSUE TITLE
Hook for setting initial session state

### ISSUE THREAD

**Issue by tcc-sejohnson** [pixelmund/svelte-kit-cookie-session#47]
It would be super cool to have a hook in `handleSession` for setting the initial session state:

```ts
const generateInitialState = () => {
  return {
    something: 'default'
  }
}

export const handle = handleSession({ 
  init: generateInitialState
});
```

This would enable us to make sure the shape of the object we're storing in sessiondata is always what we expect (and not "undefined")

**Comment by pixelmund** [comment]
Hey you can now set the initial session state with version `3.3.0`

```js
export const handle = handleSession({
	init: (event) => ({
		views: 0
	})
});
```

**Comment by tcc-sejohnson** [comment]
❤️
