### ISSUE TITLE
SvelteKit Session Cookie and Houdini

### ISSUE THREAD

**Issue by yoh-extradat** [pixelmund/svelte-kit-cookie-session#48]
Setting up a project with SvelteKit Session Cookie  and Houdini i ran into some problems and it took me a while to find a working setup. 

If is setup +layout.svelte.ts as recommended:
```ts
/** @type {import('./$types').LayoutServerLoad} */
export const load = ({ locals }) => {
	return {
		session: locals.session.data // You can also use your old `getSession` function if you wish.
	};
};
```

The houdini client receives an empty session object.
In order to solve this, I have to extent hooks.server.ts
```ts
import { handleSession } from 'svelte-kit-cookie-session';
import { sequence } from '@sveltejs/kit/hooks';
import { setSession } from '$houdini'
const sessionHandler = handleSession({
    secret: 'YOUR_SECRET_KEY'
})
export const handle = sequence(sessionHandler, ({ event, resolve }) => {
    setSession(event, event.locals.session.data) //otherwise houdini will not get the session
    return resolve(event)
})

```
Now queries work, but for mutations the client is still receiving empty session objects.
To fix this i have to manually reset **__houdini__session** in +layout.server.ts:
```ts
import { GQL_ActiveDonation } from "$houdini";
/** @type {import('./$types').LayoutServerLoad} */
export const load = async (event) => {
    const session = event.locals.session.data || null
        return {
            session: session,
            __houdini__session__: session
        }
    }
};
```
Any ideas why the recommended implementation isn't working!?

**Comment by pixelmund** [comment]
Hey, i'm currently trying to create a reproduction but getting blocked by [#751](https://github.com/HoudiniGraphql/houdini/issues/751).

I'll let you know when i find anything!
