### ISSUE TITLE
Feat: Chunked cookies

### ISSUE THREAD

**Issue by hrueger** [pixelmund/svelte-kit-cookie-session#51]
Hi @pixelmund,
first of all, thanks for this excellent library.

However, I found, that when using it to save a shopping cart for example, you can run out of space quickly. If the cookie gets too large, it is ignored by the browser. Maybe chunked cookies would be an option?

**Comment by pixelmund** [comment]
This is now available from version `3.4.0`, you'll have to opt in to the behaviour via `chunked` true on handleSession 
```ts
export const handle = handleSession({
	chunked: true,
});
```

**Comment by hrueger** [comment]
Very cool, thanks 👍
