### ISSUE TITLE
Need to expire cookies in minutes instead of days.

### ISSUE THREAD

**Issue by midnightcodr** [pixelmund/svelte-kit-cookie-session#56]
I checked the source codes a bit but can't find a way set expiration period in minutes. The only supported option is to set expiry in # of days. If setting cookies in length shorter than a day is not supported, is there a plan to do so?

**Comment by pixelmund** [comment]
You could probably do something like 0.00x to specify the expiry in minutes but i have to check if that works currently

**Comment by midnightcodr** [comment]
I tried, but unfortunately it didn’t work.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zoltan-lima** [comment]
How do you set the expiry date? I have been trying to use .set() but when I retrieve the session, the "expires" property is undefined whereas the rest of my properties are maintained.

**Comment by pixelmund** [comment]
It is now possible to set the type of expiry with the `expires_in` option, which should be of type `days | hours | minutes | seconds`
